export const STOCK_SELECTED = 'STOCK_SELECTED';
export const WATCHLIST_SELECTED = 'WATCHLIST_SELECTED';
export const FETCH_WATCHLISTS = 'FETCH_WATCHLISTS';
export const FETCH_STOCK_LIST = 'FETCH_STOCK_LIST';
export const ADD_STOCK = 'ADD_STOCK';
export const DELETE_STOCK = 'ADD_STOCK';
export const ADD_WATCHLIST = 'ADD_WATCHLIST';
export const DELETE_WATCHLIST = 'ADD_WATCHLIST';
