export const STOCK_SELECTED = 'STOCK_SELECTED';
export const FETCH_STOCK_LIST = 'FETCH_STOCK_LIST';
export const ADD_STOCK = 'ADD_STOCK';
export const DELETE_STOCK = 'DELETE_STOCK';
export const WATCHLIST_LOADING = 'WATCHLIST_LOADING';
export const ADD_WATCHLIST = 'ADD_WATCHLIST';
export const DELETE_WATCHLIST = 'DELETE_WATCHLIST';
export const WATCHLIST_SELECTED = 'WATCHLIST_SELECTED';
export const FETCH_WATCHLISTS = 'FETCH_WATCHLISTS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_ERRORS = 'GET_ERRORS';
export const WATCHLIST_ERROR = 'WATCHLIST_ERROR';
export const STOCK_LIST_ERROR = 'STOCK_LIST_ERROR';
export const UPDATE_WATCHLIST = 'UPDATE_WATCHLIST';
export const STOCK_LIST_LOADING = 'STOCK_LIST_LOADING';
export const SET_SELECTED = 'SET_SELECTED';
export const CLEAR_WATCHLIST_ERRORS = 'CLEAR_WATCHLIST_ERRORS';
export const CLEAR_WATCHLIST = 'CLEAR_WATCHLIST';
export const GET_WATCHLIST_ERRORS = 'GET_WATCHLIST_ERRORS';
export const RENAME_WATCHLIST = 'RENAME_WATCHLIST';
export const WATCHLIST_TITLE = 'WATCHLIST_TITLE';
export const CHANGE_NUMBER = 'CHANGE_NUMBER';
export const DRAG_STOCK_ORDER = 'DRAG_STOCK_ORDER';


